#ifndef WINE_NX_HORIZON_RUNTIME_PATHS_H
#define WINE_NX_HORIZON_RUNTIME_PATHS_H

#define WINE_NX_SHARED_ROOT "sdmc:/switch/wine"
#define WINE_NX_RUNTIME_ROOT WINE_NX_SHARED_ROOT
#define WINE_NX_RUNTIME_DOS_ROOT "\\??\\Z:\\switch\\wine"
#define WINE_NX_RUNTIME_DRIVE_C WINE_NX_RUNTIME_ROOT "/drive_c"
#define WINE_NX_RUNTIME_WINDOWS WINE_NX_RUNTIME_DRIVE_C "/windows"
#define WINE_NX_RUNTIME_SYSTEM32 WINE_NX_RUNTIME_WINDOWS "/system32"
#define WINE_NX_RUNTIME_SYSWOW64 WINE_NX_RUNTIME_WINDOWS "/syswow64"
#define WINE_NX_RUNTIME_NRO WINE_NX_RUNTIME_ROOT "/wine-nx-runtime.nro"

#endif
