#!/usr/bin/env python3
"""Embed the launcher's icons, assets/*.svg, in source/launcher_icons.h.

Each file's view box and the "d" of its one path go into the header, which
source/launcher_svg.c fills at the size the launcher draws them. Run this after
adding or changing an icon; with --check it only reports whether the header is
current, which tests/check-launcher-host.sh does."""
from pathlib import Path
import re
import sys

horizon_wine = Path(__file__).resolve().parents[1]
header = horizon_wine / 'source/launcher_icons.h'


def c_string(text):
    return '"' + text.replace('\\', '\\\\').replace('"', '\\"') + '"'


def generate():
    out = ['/* Generated by tools/make-launcher-icons.py from the SVG files in assets/; run it',
           ' * again after changing them. */',
           '#ifndef WINE_NX_LAUNCHER_ICONS_H',
           '#define WINE_NX_LAUNCHER_ICONS_H',
           '',
           'struct launcher_svg_icon',
           '{',
           '    float x, y, width, height;    /* the view box */',
           '    const char *d;',
           '};',
           '']
    assets = horizon_wine / 'assets'
    for svg in sorted([*assets.glob('*.svg'), *assets.glob('controls/buttons/*.svg')]):
        text = svg.read_text()
        view_box = re.search(r'viewBox="([^"]+)"', text)
        paths = re.findall(r'<path\b[^>]*\sd="([^"]+)"', text)
        assert view_box, f'{svg.name} has no viewBox'
        assert len(paths) == 1, f'{svg.name} has {len(paths)} paths; the launcher fills one'
        x, y, w, h = view_box.group(1).replace(',', ' ').split()
        # A licence notice in the file (Font Awesome's <!--! ... -->) stays with the path.
        notices = [n.strip() for n in re.findall(r'<!--!?(.*?)-->', text, re.S)]
        name = re.sub(r'[^a-z0-9]+', '_', svg.stem.lower()).strip('_')
        if svg.parent != assets:
            name = 'input_' + name
        out.append(f'/* assets/{svg.relative_to(assets).as_posix()}' + (f': {" ".join(notices)}' if notices else '') + ' */')
        out.append(f'static const struct launcher_svg_icon icon_{name} =')
        out.append(f'    {{ {x}, {y}, {w}, {h}, {c_string(paths[0])} }};')
        out.append('')
    out.append('#endif')
    return '\n'.join(out) + '\n'


text = generate()
if '--check' in sys.argv[1:]:
    if not header.exists() or header.read_text() != text:
        sys.exit(f'{header} does not match assets/*.svg; run tools/make-launcher-icons.py')
else:
    header.write_text(text)
    print(header)
